all: ieee

ieee: ieee.o
	ld -o ieee ieee.o

# odejmowanie: odejmowanie.o
# 	ld -o odejmowanie odejmowanie.o

# mnozenie: mnozenie.o
# 	ld -o mnozenie mnozenie.o

# %.o: %.s
# 	as -o $@ $<

clean:
	rm -f *.o ieee # odejmowanie mnozenie

# .PHONY: all clean